### ISSUE TITLE
MKLでのエラー

### ISSUE THREAD

**Issue by kokitsuyuzaki** [hayamizu-lab/treefit-r#1]
treefitがCRANから削除されているようです。
https://cloud.r-project.org/web/packages/treefit/index.html

原因は、`test-treefit.R`での`calculate_low_dimension_laplacian_eigenvectors()`の出力が、ハードコードされた数値と異なるためだと思われます。
https://cran-archive.r-project.org/web/checks/2021/2021-03-29_check_results_treefit.html

おそらくBLASの実装がMKLかOpenBLASかで結果が変わっているのだと予想していますが、これら実装が違うと、固有ベクトルの符号が反転する場合があるのと、小数点以下何位かで値がずれてくるので、

https://github.com/hayamizu-lab/treefit-r/blob/7ccd30e813c341e25dece3b9e58aff70c8a08ee2/tests/testthat/test-treefit.R#L86-L90

の部分は、例えば

```
  expect_equal(c(0.44170,
                 0.42532,
                 0.39847,
                 0.36180),
               abs(eigenvectors[1, ]))
```

https://github.com/hayamizu-lab/treefit-r/blob/7ccd30e813c341e25dece3b9e58aff70c8a08ee2/tests/testthat/test-treefit.R#L101-L105

の部分は、

```
  expect_equal(c(0.94948,
                 0.76344,
                 0.57019,
                 0.06708),
               calculate_canonical_correlation(eigenvectors1, eigenvectors2))
```

としてみてはいかがでしょうか。

**Comment by kou** [comment]
おぉ。。。
全然気づいていませんでした。。。
最後のcheckの日が2021-03-29ということはそのときから削除されていたということですよね。。。

その変更でよさそうな気がするのでpull requestにしてもらえますか！？

M1のMacでのCIも追加したいですが、GitHub Actionsではまだ使えないんですよねぇ。。。

**Comment by kokitsuyuzaki** [comment]
テスト部分だけを書き換えてPRしておきました。
`R CMD CHECK`や、バージョンの変更などはしてません。
特に問題なさそうであれば、CRANに再投稿をお願いします。
https://github.com/hayamizu-lab/treefit-r/pull/2

**Comment by kou** [comment]
ありがとうございます！
R 4.1での確認とかもろもろやったらCRANに出しておきます！

**Comment by kou** [comment]
CRANにsubmitしました！
スムーズにいけば今週中にでも復活すると思います！
（機能追加はないのでCRANの環境でのテストが通りさえすればスムーズにいくはず。）

**Comment by kou** [comment]
復活しました！

https://cran.r-project.org/package=treefit
